baseURL       = "https://beemom-qag6o.ondigitalocean.app/"
languageCode  = "es-mx"
title         = "Bee Mom"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Inicio"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Nosotros"
    url     = "about"
    weight  = 2
  # [[menu.nav]]
  #   name    = "Portfolio"
  #   url     = "portfolio"
  #   weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contacto"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Bee Mom | Plataforma de asesoramiento en la maternidad."
  author = "DiegoAGtz"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/I5zGF7w"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nombre(s)"
    placeholder_last_name         = "Apellidos"
    placeholder_email             = "Email"
    placeholder_project_type      = "¿Estas embarazada?"
    placeholder_about_the_project = "Dinos que piensas"
    send_message                  = "Enviar mensaje"

    [[params.contactForm.projectType]]
      value = "Sí"
      title  = "Sí"
    [[params.contactForm.projectType]]
      value = "No"
      title  = "No"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/BEE MOM PORTADA.jpg"
    heading               = "Todo lo que necesitas en tu Red de apoyo de confianza."
    tagline               = "NO ES FÁCIL PERO VALE LA PENA"
    primary_button        = "Instagram"
    primary_button_url    = "https://www.instagram.com/beemom2023"
    secondary_button      = "Contáctanos"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "¿Necesitas ayuda?"
    primary_button        = "Instagram"
    primary_button_url    = "https://www.instagram.com/beemom2023"
    secondary_button      = "Contáctanos"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Información de contacto"
      address = "Salamanca<br>Irapuato"
      # phone   = "409-896-1444"
      # email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Mapa del Sitio"
        [[params.footer.sitemap.link]]
          name = "Sobre Nosotros"
          url  = "about"
        # [[params.footer.sitemap.link]]
        #   name = "Projects"
        #   url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contacto"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Redes Sociales"
        # [[params.footer.social.link]]
        #   name = "Medium"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Behance"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Dribbble"
        #   url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/beemom2023"
      # Footer Service
      [params.footer.service]
        title       = "Brindamos:"
        description = "Asesoría en tu proceso de<br>maternidad, consejos, entrevistas<br>y recomendaciones."